### ISSUE TITLE
No container build for Arm64 Platform

### ISSUE THREAD

**Issue by leptoquark1** [kalbasit/signal-api-receiver#41] opened 2024-12-27 20:29 UTC
Hey,

it would be great if there is a way for you to build the container for ARM Platform too. This would reduce additional workload for deployment setups using e.g Rasberry Pi

regards

**Comment by kalbasit** [comment] 2024-12-27 23:49
@leptoquark1 can you provide the output of `uname -a` on your R-Pi?

**Comment by kalbasit** [comment] 2024-12-28 20:06
@leptoquark1 I added support for `aarch64-linux` in #42, can you please try the image? I don't have an R-pi to test it on.

```bash
docker pull kalbasit/signal-api-receiver:pr-42@sha256-2c851b37f5a126bb68257c5cdd3b1c7fea77b5c4a8ae0fad34233b4d52c953dd
```

**Comment by kalbasit** [comment] 2024-12-28 23:50
Although I was not able to test it, I confirmed running it locally fails due to mimatch platform
```
docker run kalbasit/signal-api-receiver:pr-42@sha256:89e792893828a77db6c99237888d2c1a0bf724de59c4fd0d796f274cc9d5b55f
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
exec /bin/signal-api-receiver: exec format error
```

I'm going to go ahead and merge #42 and close this ticket. Please re-open if it does not work for you.

**Closed** 2024-12-29 00:32 UTC
